# Generated by Django 3.1.14 on 2022-05-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Provide a title with maximum of 256 letters', max_length=256)),
                ('slug', models.SlugField(help_text='Please enter a unique slug', max_length=256, unique=True)),
                ('text', models.TextField(blank=True, help_text='Provide for the article')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
