# Generated by Django 3.1.14 on 2022-04-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfoModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_maininfomodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Hlavní Informace', help_text='Titulek hlavní info sekce (<h3>)', max_length=64)),
                ('text', models.TextField(help_text='Text zobrazený v hlavní info sekce (<p>)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='welcomemodel',
            name='welcome_text',
            field=models.CharField(default='Vítejte na Merkit', help_text='Hlavní uvítací text (<h1>)', max_length=255),
        ),
    ]
