# Generated by Django 3.1.14 on 2022-07-05 14:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_linkmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(help_text='Titulek linku.', max_length=64)),
                ('href', models.CharField(help_text='ID sekce na kterou link odkazuje, ID začínají #, url /.', max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ServiceDetailModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_servicedetailmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(help_text='Titulek detailu služeb.', max_length=64)),
                ('text', models.TextField(help_text='Text popisující službu.')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('references', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_servicemodel', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(help_text='Rozeznávací jméno služby, musí být unikátní.', max_length=64)),
                ('title', models.CharField(help_text='Titul služby.', max_length=64)),
                ('image', models.ImageField(upload_to='images/')),
                ('back_title', models.CharField(help_text='Titul služby na zadní straně karty.', max_length=64)),
                ('back_text', models.TextField(help_text='Text na zadní straně karty.')),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_servicesmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Služby', help_text='Titulek služeb.', max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='welcomemodel',
            name='link_href',
            field=models.CharField(default='welcome', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welcomemodel',
            name='link_title',
            field=models.CharField(default='welcome', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welcomemodel',
            name='show_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='welcomemodel',
            name='welcome_text',
            field=models.CharField(default='Vítejte na Merkit', help_text='Hlavní uvítací text.', max_length=255),
        ),
        migrations.CreateModel(
            name='MainInfoModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_maininfomodel', serialize=False, to='cms.cmsplugin')),
                ('show_link', models.BooleanField(default=False)),
                ('link_title', models.CharField(max_length=64)),
                ('link_href', models.CharField(max_length=64)),
                ('title', models.CharField(default='Hlavní Informace', help_text='Titulek hlavní info sekce.', max_length=64)),
                ('text', models.TextField(help_text='Text zobrazený v hlavní info sekce.')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins_app.linkmanager')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_contactformmodel', serialize=False, to='cms.cmsplugin')),
                ('show_link', models.BooleanField(default=False)),
                ('link_title', models.CharField(max_length=64)),
                ('link_href', models.CharField(max_length=64)),
                ('title', models.CharField(default='Kontakt', help_text='Titulek formuláře kontaktu.', max_length=64)),
                ('text', models.TextField(blank=True, help_text='Text zobrazený pod titulkem.')),
                ('email_label', models.CharField(default='Email', help_text='Popis pole pro zadání emailu.', max_length=32)),
                ('name_label', models.CharField(default='Jméno', help_text='Popis pole pro zadání křestního jména.', max_length=32)),
                ('surname_label', models.CharField(default='Příjmení', help_text='Popis pole pro zadání příjmení.', max_length=32)),
                ('phone_label', models.CharField(default='Telefonní číslo', help_text='Popis pole pro zadání telefonního čísla.', max_length=32)),
                ('subject_label', models.CharField(default='Předmět', help_text='Popis pole pro zadání předmětu.', max_length=32)),
                ('message_label', models.CharField(default='Zpráva', help_text='Popis pole pro zadání těla zprávy.', max_length=32)),
                ('confirmation', models.TextField(blank=True, help_text='Souhlas s podmínkami.')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins_app.linkmanager')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='welcomemodel',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plugins_app.linkmanager'),
            preserve_default=False,
        ),
    ]
