# Generated by Django 3.1.14 on 2022-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0002_auto_20220404_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomodel',
            name='text',
            field=models.TextField(help_text='Text zobrazený v hlavní info sekce (p)'),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='title',
            field=models.CharField(default='Hlavní Informace', help_text='Titulek hlavní info sekce (h3)', max_length=64),
        ),
        migrations.AlterField(
            model_name='welcomemodel',
            name='welcome_text',
            field=models.CharField(default='Vítejte na Merkit', help_text='Hlavní uvítací text (h1)', max_length=255),
        ),
    ]
