# Generated by Django 3.1.14 on 2022-07-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0002_auto_20220705_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plugins_app.linkmanager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='link_href',
            field=models.CharField(default='service', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='link_title',
            field=models.CharField(default='service', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='show_link',
            field=models.BooleanField(default=False),
        ),
    ]
