# Generated by Django 3.1.14 on 2022-04-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins_app', '0003_auto_20220404_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_contactformmodel', serialize=False, to='cms.cmsplugin')),
                ('email_label', models.CharField(default='Email', help_text='Popis pole pro zadání emailu.', max_length=32)),
                ('name_label', models.CharField(default='Jméno', help_text='Popis pole pro zadání křestního jména.', max_length=32)),
                ('surname_label', models.CharField(default='Příjmení', help_text='Popis pole pro zadání příjmení.', max_length=32)),
                ('phone_label', models.CharField(default='Telefonní číslo', help_text='Popis pole pro zadání telefonního čísla.', max_length=32)),
                ('subject_label', models.CharField(default='Předmět', help_text='Popis pole pro zadání předmětu.', max_length=32)),
                ('message_label', models.CharField(default='Zpráva', help_text='Popis pole pro zadání těla zprávy.', max_length=32)),
                ('confirmation', models.TextField(help_text='Souhlas s podmínkami.')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='text',
            field=models.TextField(help_text='Text zobrazený v hlavní info sekce.'),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='title',
            field=models.CharField(default='Hlavní Informace', help_text='Titulek hlavní info sekce.', max_length=64),
        ),
        migrations.AlterField(
            model_name='welcomemodel',
            name='welcome_text',
            field=models.CharField(default='Vítejte na Merkit', help_text='Hlavní uvítací text.', max_length=255),
        ),
    ]
