# Generated by Django 3.1.14 on 2022-07-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins_app', '0003_auto_20220705_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkModel',
        ),
    ]
