# Generated by Django 3.1.14 on 2022-04-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0004_auto_20220404_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='text',
            field=models.TextField(default='Text', help_text='Text zobrazený pod titulkem.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactformmodel',
            name='title',
            field=models.CharField(default='Kontakt', help_text='Titulek formuláře kontaktu.', max_length=64),
        ),
    ]
