# Generated by Django 3.1.14 on 2022-04-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0005_auto_20220404_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='confirmation',
            field=models.TextField(blank=True, help_text='Souhlas s podmínkami.'),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='text',
            field=models.TextField(blank=True, help_text='Text zobrazený pod titulkem.'),
        ),
    ]
