# Generated by Django 3.1.14 on 2022-07-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0005_auto_20220710_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformmodel',
            old_name='link',
            new_name='link_manager',
        ),
        migrations.RenameField(
            model_name='maininfomodel',
            old_name='link',
            new_name='link_manager',
        ),
        migrations.RenameField(
            model_name='servicesmodel',
            old_name='link',
            new_name='link_manager',
        ),
        migrations.RenameField(
            model_name='welcomemodel',
            old_name='link',
            new_name='link_manager',
        ),
    ]
