# Generated by Django 3.1.14 on 2022-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0006_auto_20220710_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='button_text',
            field=models.CharField(default='Odeslat', help_text='Text zobrazený na tlačítku odeslání.', max_length=32),
        ),
    ]
