# Generated by Django 3.1.14 on 2022-04-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins_app', '0007_servicesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_servicemodel', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(help_text='Rozeznávací jméno služby, musí být unikátní.', max_length=64, unique=True)),
                ('title', models.CharField(help_text='Titul služby', max_length=64)),
                ('image', models.ImageField(upload_to='images/')),
                ('back_title', models.CharField(help_text='Titul služby na zadní straně karty', max_length=64)),
                ('back_text', models.TextField(help_text='Text na zadní straně karty.')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='servicesmodel',
            name='cards',
        ),
    ]
