# Generated by Django 3.1.14 on 2022-04-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0008_auto_20220404_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
