# Generated by Django 3.1.14 on 2022-07-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0008_auto_20220728_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmodel',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='contactformmodel',
            name='email_label',
        ),
        migrations.RemoveField(
            model_name='contactformmodel',
            name='message_label',
        ),
        migrations.RemoveField(
            model_name='contactformmodel',
            name='name_label',
        ),
        migrations.RemoveField(
            model_name='contactformmodel',
            name='phone_label',
        ),
        migrations.RemoveField(
            model_name='contactformmodel',
            name='subject_label',
        ),
        migrations.RemoveField(
            model_name='contactformmodel',
            name='surname_label',
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='confirmation',
            field=models.TextField(blank=True, help_text='Agree to terms.'),
        ),
    ]
