# Generated by Django 3.1.14 on 2022-04-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0009_auto_20220404_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
