# Generated by Django 3.1.14 on 2022-07-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0009_auto_20220728_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='confirmation',
            field=models.TextField(blank=True, help_text='Agreement with the terms.'),
        ),
    ]
