# Generated by Django 3.1.14 on 2022-08-30 12:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0010_auto_20220728_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetailmodel',
            name='references',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
