# Generated by Django 3.1.14 on 2022-08-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0011_auto_20220830_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='link_href',
            field=models.CharField(blank=True, help_text='ID that will be appended to the section.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='link_manager',
            field=models.ForeignKey(help_text='Please select Link Manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plugins_app.linkmanager'),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='link_title',
            field=models.CharField(blank=True, help_text='Title that will be shown in Nav Link Plugin.', max_length=64),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='show_link',
            field=models.BooleanField(default=False, help_text='If selected, the link will be shown in the Nav Link Plugin.'),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='link_href',
            field=models.CharField(blank=True, help_text='ID that will be appended to the section.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='link_manager',
            field=models.ForeignKey(help_text='Please select Link Manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plugins_app.linkmanager'),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='link_title',
            field=models.CharField(blank=True, help_text='Title that will be shown in Nav Link Plugin.', max_length=64),
        ),
        migrations.AlterField(
            model_name='maininfomodel',
            name='show_link',
            field=models.BooleanField(default=False, help_text='If selected, the link will be shown in the Nav Link Plugin.'),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='link_href',
            field=models.CharField(blank=True, help_text='ID that will be appended to the section.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='link_manager',
            field=models.ForeignKey(help_text='Please select Link Manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plugins_app.linkmanager'),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='link_title',
            field=models.CharField(blank=True, help_text='Title that will be shown in Nav Link Plugin.', max_length=64),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='show_link',
            field=models.BooleanField(default=False, help_text='If selected, the link will be shown in the Nav Link Plugin.'),
        ),
        migrations.AlterField(
            model_name='welcomemodel',
            name='link_href',
            field=models.CharField(blank=True, help_text='ID that will be appended to the section.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='welcomemodel',
            name='link_manager',
            field=models.ForeignKey(help_text='Please select Link Manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plugins_app.linkmanager'),
        ),
        migrations.AlterField(
            model_name='welcomemodel',
            name='link_title',
            field=models.CharField(blank=True, help_text='Title that will be shown in Nav Link Plugin.', max_length=64),
        ),
        migrations.AlterField(
            model_name='welcomemodel',
            name='show_link',
            field=models.BooleanField(default=False, help_text='If selected, the link will be shown in the Nav Link Plugin.'),
        ),
    ]
