# Generated by Django 3.1.14 on 2022-04-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins_app', '0011_auto_20220411_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetailModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_servicedetailmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(help_text='Titulek detailu služeb.', max_length=64)),
                ('text', models.TextField(help_text='Text popisující službu.')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='back_title',
            field=models.CharField(help_text='Titul služby na zadní straně karty.', max_length=64),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='title',
            field=models.CharField(help_text='Titul služby.', max_length=64),
        ),
    ]
