# Generated by Django 3.1.14 on 2022-04-23 15:35

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins_app', '0012_auto_20220422_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetailmodel',
            name='references',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='references', to='cms.placeholder'),
        ),
    ]
