# Generated by Django 3.1.14 on 2022-04-23 15:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0013_servicedetailmodel_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetailmodel',
            name='references',
            field=tinymce.models.HTMLField(default='Next'),
            preserve_default=False,
        ),
    ]
