# Generated by Django 3.1.14 on 2022-11-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins_app', '0013_auto_20220830_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerkitNavbarModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_merkitnavbarmodel', serialize=False, to='cms.cmsplugin')),
                ('logo', models.ImageField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
