# Generated by Django 3.1.14 on 2022-11-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0015_remove_servicedetailmodel_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetailmodel',
            name='text',
        ),
    ]
