# Generated by Django 3.1.14 on 2022-05-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins_app', '0015_welcomemodel_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='link_id',
            field=models.CharField(default='contact_section', help_text='ID sekce pro linkovací důvody.', max_length=64),
        ),
        migrations.AddField(
            model_name='maininfomodel',
            name='link_id',
            field=models.CharField(default='main_info_section', help_text='ID sekce pro linkovací důvody.', max_length=64),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='link_id',
            field=models.CharField(default='services_section', help_text='ID sekce pro linkovací důvody.', max_length=64),
        ),
    ]
