# Generated by Django 3.1.14 on 2022-05-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins_app', '0016_auto_20220530_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_app_linkmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(help_text='Titulek linku.', max_length=64)),
                ('href', models.CharField(help_text='ID sekce na kterou link odkazuje, ID začínají #.', max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
